### ISSUE TITLE
Q: Tracking points, rotations, etc.

### ISSUE THREAD

**Issue by ib00** [jtsiomb/libanim#1] opened 2024-11-10 12:38 UTC
What is a recommended way of tracking values other than scalars (eg, points, rotations, transformations)?

At the moment it seems the only way to do it is to create three tracks to track a point as opposed to a single track with a 
tuple as a value.

Thanks.

**Comment by jtsiomb** [comment] 2024-11-10 14:00
libanim has two levels you can use: the low level keyframe tracks stuff in track.h, and the high level animation node system in anim.h.

Track interface
----------------------
track.h is all about the basic "set keyframe", "evaluate at time t", "interpolation/extrapolation" operations, and it works on single valued keyframe tracks, just time/value pairs. The idea as you noticed is that to animate a position, you'd have a higher level abstraction which sets keyframes to three tracks, evaluate three tracks to figure out the position at time t, etc. 

### Quaternions
That works great for position and scale, but rotation quaternions need special interpolation (slerp). This used to be handled by the higher level interface initially, but since the animation interface is not always appropriate for all projects, and it's useful to be able to use the low level interface only, the *last* commit adds `anm_get_quat` which takes 4 tracks, and evaluates them as a rotation quaternion.

Animation node interface
-------------------------------------
Initially this was supposed to be "the" API for this library, but over time it turns out it's maybe too high level and contains abstractions which the application might want to design differently and handle by itself more integrated with the rest of its scene management. So it doesn't necessarilly fit into every application.

This interface is centered around the `anm_node` structure, which represents a hierarchical transformation node which can be part of a 3D object. Calling `anm_set_position`, `anm_set_rotation` and so on to it automatically sets keyframes to the "default animation" used by that node (you can have multiple animations and switch/blend between them). And you can then just `anm_get_matrix` for a specific time, and it will evaluate all 10 tracks for that time, combine position/rotation/scaling, and give you back a matrix. The matrix will also be cached, so if you ask multiple times for the matrix for the same time, it won't have to be re-evaluated, and this works with thread-local storage to avoid multithreading issues. If it's a child node, it will recurse up and evaluate its parent, and combine its matrix too (or you could use `anm_get_node_matrix` if you don't want to concatenate with patent).

That's pretty useful for a wide range of apps, and it will completely automatically handle all the details of maintaining multiple low level tracks and interpolating them and so on. But again, there are cases where these mechanisms are better suited for handling within the application, in which case you'd just ignore anything in `anim.h` and use `track.h` directly in your own abstractions.

Also, if you want to use multiple animations, and especially in node hierarchies, you can probably do a better design than what I have here. That part is a bit awkward. It works, but I don't like the way it ended up.

Hope this helps, feel free to ask followup questions. I'm closing the issue because it's really not a bug report, but don't take that as a deterrent to post more. I just want to keep the bug trackers in my projects clean, with only outstanding bugs open.

**Closed as completed by jtsiomb** 2024-11-10 14:00 UTC

**Comment by jtsiomb** [comment] 2024-11-10 14:14
I realize this information is not spelled out anywhere, so I added a slightly reworked version of my response to the readme file. And I'll go ahead and prepare a release with all the latest changes.

**Comment by ib00** [comment] 2024-11-10 16:42
Thank you for the library and your detailed reply. Much appreciated!
